### ISSUE TITLE
Pico8 support

### ISSUE THREAD

**Issue by deepnight** [FunKey-Project/FunKey-Project.github.io#2]
Hi!

My name is Sebastien Benard, former lead dev on Dead Cells (and living in Bordeaux too btw!)

Do you think it would be possible to have some support for Pico8 games (a virtual console). It's super popular among indie devs around the world and I'm pretty confident it would be an amazing marketing move to announce. The Funkey S format is perfect for this console and this could open some new interesting channels with a *very* strong dev community. 

What do  you think?

**Comment by Michel-FK** [comment]
Hi Sébastien,

There are at least 2 reasons why porting retro8 to the FunKey is difficult:

- retro8 is not open source, so we need to ask the original developers to port it to the FunKey S
- Retro8 is using the SDL2 and 3D graphics with shaders and thus requires a GPU, which the FunKey S does not have

**Comment by Michel-FK** [comment]
Not pico8 per se, but we just added retro8-libretro, which is a free pico8 clonefor libretro, which should be more or less compatible.
