### ISSUE TITLE
How to SSH to the device

### ISSUE THREAD

**Issue by hxhieu** [FunKey-Project/FunKey-Project.github.io#5]
Hi and thanks for the awesome device but I've noticed that the SSH section in the documentation has been empty for awhile.
Is it going to be updated soon or any quick instruction we can share here?

**Comment by Alan-Cha** [comment]
I am also interested in how to SSH into my device. I have some issues that I need to resolve.

**Comment by hxhieu** [comment]
@Alan-Cha I would suggest you join the Discord, I think they are more active there.
I got the SSH working with this instruction 
![image](https://user-images.githubusercontent.com/781299/115310376-d50b9c00-a1c1-11eb-9874-cfe667d03868.png)
