### ISSUE TITLE
Coolie Coolster Artwork Files

### ISSUE THREAD

**Issue by oduska** [FunKey-Project/FunKey-Project.github.io#6]
The Google Drive link no longer works.

https://drive.google.com/drive/folders/1UY4J8b6eMtG_IEtvHLOqGLm-DSgMkokA

**Comment by Coolie2** [comment]
Here's the new link (https://drive.google.com/drive/folders/1k55I5ig_wISP5RGjnH6K63H4LV9s-g3U?usp=sharing), and I submitted a pull request to fix it.

**Comment by DrUm78** [comment]
Updated link has been pushed. 👍
