### ISSUE TITLE
Rebuild/deploy needed - firmware link is out of date

### ISSUE THREAD

**Issue by andypiper** [FunKey-Project/FunKey-Project.github.io#7]
I noticed that the link to the latest firmware image on [this page](https://doc.funkey-project.com/user_manual/tutorials/hardware/flash_change_sd_card/) points to the v2.1.0 .fwu file, but the latest is v2.3.0 (and the image shows 2.0.1 .img). This was already fixed in commit 17945e9addad4c7b3fd7a0a70da2244ffb6ba16e so there is no point in me sending a PR! 🙂 

Also, shouldn't this link direct users to download the flashable .img file, not the .fwu file, in this tutorial?

**Comment by DrUm78** [comment]
Link and pic were already fixed. We won't update the pics each time we change the revision number though, they are there for reference.
